### ISSUE TITLE
Trident and spyglass look wrong

### ISSUE THREAD

**Issue by legosteenjaap** [gliscowo/interactic#1]
![2021-09-07_22 31 35](https://user-images.githubusercontent.com/50271899/132407026-b2d3a5bd-e8a4-4ab6-a266-c9a37e6b0e22.png)

**Comment by gliscowo** [comment]
Both of these items have hardcoded exceptions in the rendering engine, which I don't wanna work around because that would mean potentially adding more special cases for other weird items which can easily become a never ending cycle and a beast to maintain. In your specific case I would actually also suspect some other rendering mod being at fault as both of these items should usually use their texture when dropped on the ground.
